
AngryAssign_Pages = {
	[414441359] = {
		["Updated"] = 1690224305,
		["Name"] = "Gruul N",
		["Backup"] = "Healers positioning\n||cred-------------------\n        H4 {rt4}        H3 {rt3}\n   \n                   {rt8}\n  H5 {rt5}    |credGruul||r     H2 {rt2}\n                   {rt8}\n\n               H1 {rt1}\n          ||cpurpleEntrance||r\n\nNotable abilities:\n||cred-------------------\n{icon trade_engineering} |credHurtful Strike:||r physical damage to second highest threat\n{icon inv_stone_11} |credGround Slam + {icon ability_bullrush} Shatter:||r AoE Knockback + proximity damage after 5s\n{icon spell_holy_improvedresistanceauras} |credReverberation:||r 4s AoE silence (every 40-56s)\n{icon ability_golemstormbolt} |credCave In:||r void zone with periodic damage, visible in debuffs, initial CD 30s and -1.5s each time it is cast\n{icon spell_shadow_charm} ||credSoft enrage:||r +15% damage each 30s\n\n{tank} ||cwarriorTanks\n||cred-------------------\n{rt6} + {rt7}, must be highest on aggro due to Hurtful Strike\n\n{dps} |crogueDPS\n||cred-------------------\nWatch your aggro, don't go above tanks\n{hunter} |chunterHunters:||r Use {icon ability_hunter_misdirection}Misdirection on pull and periodically during the fight to help tanks with aggro\n{shaman} |cshamanShamans:||r {bl}BL 5sec after pull\n\n{icon ability_creature_cursed_02} Spread after AoE knockback, |credat least 13yd (/range 13)",
		["Id"] = 414441359,
		["UpdateId"] = 369296674,
		["Contents"] = "Healers positioning\n||cred-------------------\n        H4 {rt4}        H3 {rt3}\n   \n                   {rt8}\n  H5 {rt5}    |credGruul||r     H2 {rt2}\n                   {rt8}\n\n               H1 {rt1}\n          ||cpurpleEntrance||r\n\nNotable abilities:\n||cred-------------------\n{icon trade_engineering} |credHurtful Strike:||r physical damage to second highest threat\n{icon inv_stone_11} |credGround Slam + {icon ability_bullrush} Shatter:||r AoE Knockback + proximity damage after 5s\n{icon spell_holy_improvedresistanceauras} |credReverberation:||r 4s AoE silence (every 40-56s)\n{icon ability_golemstormbolt} |credCave In:||r void zone with periodic damage, visible in debuffs, initial CD 30s and -1.5s each time it is cast\n{icon spell_shadow_charm} ||credSoft enrage:||r +15% damage each 30s\n\n{tank} ||cwarriorTanks\n||cred-------------------\n{rt6} + {rt7}, must be highest on aggro due to Hurtful Strike\n\n{dps} |crogueDPS\n||cred-------------------\nWatch your aggro, don't go above tanks\n{hunter} |chunterHunters:||r Use {icon ability_hunter_misdirection}Misdirection on pull and periodically during the fight to help tanks with aggro\n{shaman} |cshamanShamans:||r {bl}BL 5sec after pull\n\n{icon ability_creature_cursed_02} Spread after AoE knockback, |credat least 13yd (/range 13)",
		["CategoryId"] = 555034898,
	},
	[588579974] = {
		["Updated"] = 1670535567,
		["Name"] = "Ouro",
		["Contents"] = "|cbluePhase 1||r\n{tank} |cwarriorTanks:||r\n - Boss is |credimmune to taunt||r so fight for aggro.\n - Only the tank that has aggro is in front of the boss.\n - |corangeSand Blast||r resets aggro if you get hit.\n\n{healer} |cgreenHealers||r and {dps} |cdeathknightDPS||r:\n - Always stay behind the boss - visual is bugged.\n   - Pets {rt2} {rt5} are always attacking from the back.\n - |corangeSweep||r (knockback) soon after |corangeSand Blast||r, be >= |cblue30yd||r away from the boss.\n\n|cbluePhase 2||r\n - Boss submerges after 4 |corangeSweeps||r.\n - |credBefore 4. Sweep run away.||r\n   - |credQuake||r spawns, run away from it and spread across the room.\n - Kill scarabs at the end of the phase.\n\n|cbluePhase 3||r\n - |credEnrage at 20%||r, use your cooldowns now.\n - Quakes spawn frequently. Melees stay at max range.",
		["Id"] = 588579974,
		["UpdateId"] = 1659953703,
		["Backup"] = "|cbluePhase 1||r\n{tank} |cwarriorTanks:||r\n - Boss is |credimmune to taunt||r so fight for aggro.\n - Only the tank that has aggro is in front of the boss.\n - |corangeSand Blast||r resets aggro if you get hit.\n\n{healer} |cgreenHealers||r and {dps} |cdeathknightDPS||r:\n - Always stay behind the boss - visual is bugged.\n   - Pets {rt2} {rt5} are always attacking from the back.\n - |corangeSweep||r (knockback) soon after |corangeSand Blast||r, be >= |cblue30yd||r away from the boss.\n\n|cbluePhase 2||r\n - Boss submerges after 4 |corangeSweeps||r.\n - |credBefore 4. Sweep run away.||r\n   - |credQuake||r spawns, run away from it and spread across the room.\n - Kill scarabs at the end of the phase.\n\n|cbluePhase 3||r\n - |credEnrage at 20%||r, use your cooldowns now.\n - Quakes spawn frequently. Melees stay at max range.",
		["CategoryId"] = 22948398,
	},
	[1583056124] = {
		["Updated"] = 1670613263,
		["Name"] = "Twin Emperors",
		["Contents"] = "- |credVek'lor:||r immune to physical damage.\n- |credVek'nilash:||r immune to magic damage.\n- Bosses can't be within 60yd of each other or they will heal.\n- |credEvery 30-40 seconds they switch places.||r\n- Keep |cblue12yd||r range when near Vek'lor (avoid |cmageblizzards||r).\n\n{tank} |cwarriorTanks:||r\n - |cblueRight:||r {rt1} {rt2} {rt3} (Warlock tank).\n - |cblueLeft:||r {rt4} {rt5} (Paladin tank with SR {icon spell_shadow_sealofkings}).\n - |credSwitch||r after Unbalancing Strike (only warriors and paladins).\n\n{healer} |cgreenHealers:||r\n - Split to two groups (left and right) based on the comp.\n\n{dps} |cdeathknightDPS:||r\n - Melee on Vek'nilash, magic on Vek'lor.\n - |credKill empowered bugs ASAP.||r\n - Start running to the opposite side of the room |cred+-5s||r before the switch.\n - Kill small bugs when running to the other side.",
		["Id"] = 1583056124,
		["UpdateId"] = 3648663356,
		["Backup"] = "- |credVek'lor:||r immune to physical damage.\n- |credVek'nilash:||r immune to magic damage.\n- Bosses can't be within 60yd of each other or they will heal.\n- |credEvery 30-40 seconds they switch places.||r\n- Keep |cblue12yd||r range when near Vek'lor (avoid |cmageblizzards||r).\n\n{tank} |cwarriorTanks:||r\n - |cblueRight:||r {rt1} {rt2} {rt3} (Warlock tank).\n - |cblueLeft:||r {rt4} {rt5} (Paladin tank with SR {icon spell_shadow_sealofkings}).\n - |credSwitch||r after Unbalancing Strike (only warriors and paladins).\n\n{healer} |cgreenHealers:||r\n - Split to two groups (left and right) based on the comp.\n\n{dps} |cdeathknightDPS:||r\n - Melee on Vek'nilash, magic on Vek'lor.\n - |credKill empowered bugs ASAP.||r\n - Start running to the opposite side of the room |cred+-5s||r before the switch.\n - Kill small bugs when running to the other side.",
		["CategoryId"] = 22948398,
	},
	[1095919676] = {
		["Updated"] = 1669666167,
		["Name"] = "Bugs: Princess Last",
		["Id"] = 1095919676,
		["UpdateId"] = 2005375580,
		["Contents"] = "",
		["CategoryId"] = 22948398,
	},
	[1574022645] = {
		["Updated"] = 1670263873,
		["Name"] = "Prophet Skeram",
		["Contents"] = "Boss splits into |cred3 copies||r at 75%, 50%, 25%.\n\nThe raid splits to the right and left stairs:\n - |cblueRight:||r Groups 2 and 4.\n - |cblueLeft:||r Groups 3 and 5.\n - ||cblueMiddle:||r Group 1 dps.\n\n{tank} |cwarriorTanks:\n{rt1} Middle, tanks boss {rt8}\n{rt2} Left\n{rt4} Right\n\n{healer} |cgreenHealers:\n - Don't heal when the copies are about to spawn to avoid death by {spell 26194}!\n\n{dps} |cdeathknightDPS:\n - Rogues and Shamans interrupt {icon ability_kick} {icon spell_nature_cyclone} every {spell 26192}!\n - Kill the copies ASAP! All copies must be killed before the next split.\n - {icon ability_creature_cursed_02} |credDon't kill players with Mind Control!\n - |cmageMages||r {mage}, |cwarlockWarlocks||r {warlock} and |cdruidDruids||r {druid} CC players with Mind Control.",
		["Id"] = 1574022645,
		["UpdateId"] = 3275680845,
		["Backup"] = "Boss splits into |cred3 copies||r at 75%, 50%, 25%.\n\nThe raid splits to the right and left stairs:\n - |cblueRight:||r Groups 2 and 4.\n - |cblueLeft:||r Groups 3 and 5.\n - ||cblueMiddle:||r Group 1 dps.\n\n{tank} |cwarriorTanks:\n{rt1} Middle, tanks boss {rt8}\n{rt2} Left\n{rt4} Right\n\n{healer} |cgreenHealers:\n - Don't heal when the copies are about to spawn to avoid death by {spell 26194}!\n\n{dps} |cdeathknightDPS:\n - Rogues and Shamans interrupt {icon ability_kick} {icon spell_nature_cyclone} every {spell 26192}!\n - Kill the copies ASAP! All copies must be killed before the next split.\n - {icon ability_creature_cursed_02} |credDon't kill players with Mind Control!\n - |cmageMages||r {mage}, |cwarlockWarlocks||r {warlock} and |cdruidDruids||r {druid} CC players with Mind Control.",
		["CategoryId"] = 22948398,
	},
	[355235451] = {
		["Updated"] = 1669844603,
		["Name"] = "Bugs: Vem Last",
		["Backup"] = "|credKill order:||r Kri {rt8} -> Yauj {rt7} -> Vem {rt6}\n\nBoss positions in the room: \n - |cblueLeft:||r Yauj {rt7}. Tanked by {rt1}.\n - |cblueMiddle:||r Kri {rt8}. Tanked by {rt2}.\n - |cblueRight:||r Vem {rt6}. Tanked by {rt4} in one of the alcoves.\n\nKri {rt8}: Cleave, |cgreenToxic Volley||r, |credDeath = Poison Cloud||r.\nYauj {rt7}: |cwarlockAoE Fear||r (resets threat), |credHeal||r, Dispel. Death = Adds.\nVem {rt6}: Knocks away tank, charges random player in LoS.\n\n{shaman} |cshamanShamans:||r Tremor Totem {icon spell_nature_tremortotem}, Cleansing Totem {icon spell_nature_diseasecleansingtotem}\n{healer} |cgreenHealers:||r Dispel poison and fear.\n{dps} {tank} |cdeathknightDPS||r, |cwarriorTanks:||r Don't die and interrupt Yauj's heal.",
		["Id"] = 355235451,
		["UpdateId"] = 3416288303,
		["Contents"] = "|credKill order:||r Kri {rt8} -> Yauj {rt7} -> Vem {rt6}\n\nBoss positions in the room: \n - |cblueLeft:||r Yauj {rt7}. Tanked by {rt1}.\n - |cblueMiddle:||r Kri {rt8}. Tanked by {rt2}.\n - |cblueRight:||r Vem {rt6}. Tanked by {rt4} in one of the alcoves.\n\nKri {rt8}: Cleave, |cgreenToxic Volley||r, |credDeath = Poison Cloud||r.\nYauj {rt7}: |cwarlockAoE Fear||r (resets threat), |credHeal||r, Dispel. Death = Adds.\nVem {rt6}: Knocks away tank, charges random player in LoS.\n\n{shaman} |cshamanShamans:||r Tremor Totem {icon spell_nature_tremortotem}, Cleansing Totem {icon spell_nature_diseasecleansingtotem}\n{healer} |cgreenHealers:||r Dispel poison and fear.\n{dps} {tank} |cdeathknightDPS||r, |cwarriorTanks:||r Don't die and interrupt Yauj's heal.",
		["CategoryId"] = 22948398,
	},
	[1416669210] = {
		["Updated"] = 1690036154,
		["Name"] = "C'thun",
		["Contents"] = "|cbluePhase 1:||r\n      |cred0, 2, 4, ... glares||r            ||          ||cred1, 3, 5, ... glares||r\n -----------------------------------------------------------\n       G4 {rt2}        G5 {rt6}                                    G1 {rt3} \n                                             \n                  {rt8}                                                  {rt8}\n  G3 {rt1}    Boss      G2 {rt4}                 G2 {rt4}    Boss      G3 {rt1}\n                  {rt8}                                                  {rt8}\n\n               G1 {rt3}                                    G5 {rt6}        G4 {rt2}\n          |cpurpleEntrance||r                                       ||cpurpleEntrance||r\n\n - |credRange check 13yd.|cred\n - |credBeware the Dark Glare {icon ability_creature_cursed_02}.||r Everyone rotates 180%.\n\n|cbluePhase 2:||r\n - Move close to the room entrance and spread a bit.\n - |crogueCC and kick||r the big eye tentacles.\n - Snare removing abilities remove the small eyes' Mind Flay. \n    - {shaman} |cshamanShamans:||r Improved earthbind totem.\n    - {paladin} |cpaladinPaladins:||r Hand of Freedom.\n    - etc.\n\n - |credAlways stay in the first half of the room.||r\n   - |cdeathknightMelees||r kill small eyes that are in the first half of the room.\n   - |chunterRanged||r kill the ones in the back.\n\n  |cbluePositions when small eyes spawn:||r\n\n                           {rt7} Ranged eyes {rt7}\n                                \n  |cred--------------------||r {rt8} Boss {rt8} |cred--------------------||r\n     |chunterRanged players||r                 ||chunterRanged players||r\n                           {rt7} Melee eyes {rt7}\n               |cdeathknightMelee players||r     ||cdeathknightMelee players||r\n                                  ||cpurpleEntrance||r",
		["Id"] = 1416669210,
		["UpdateId"] = 3955379146,
		["Backup"] = "|cbluePhase 1:||r\n      |cred0, 2, 4, ... glares||r            ||          ||cred1, 3, 5, ... glares||r\n -----------------------------------------------------------\n       G4 {rt2}        G5 {rt6}                                    G1 {rt3} \n                                             \n                  {rt8}                                                  {rt8}\n  G3 {rt1}    Boss      G2 {rt4}                 G2 {rt4}    Boss      G3 {rt1}\n                  {rt8}                                                  {rt8}\n\n               G1 {rt3}                                    G5 {rt6}        G4 {rt2}\n          |cpurpleEntrance||r                                       ||cpurpleEntrance||r\n\n - |credRange check 13yd.|cred\n - |credBeware the Dark Glare {icon ability_creature_cursed_02}.||r Everyone rotates 180%.\n\n|cbluePhase 2:||r\n - Move close to the room entrance and spread a bit.\n - |crogueCC and kick||r the big eye tentacles.\n - Snare removing abilities remove the small eyes' Mind Flay. \n    - {shaman} |cshamanShamans:||r Improved earthbind totem.\n    - {paladin} |cpaladinPaladins:||r Hand of Freedom.\n    - etc.\n\n - |credAlways stay in the first half of the room.||r\n   - |cdeathknightMelees||r kill small eyes that are in the first half of the room.\n   - |chunterRanged||r kill the ones in the back.\n\n  |cbluePositions when small eyes spawn:||r\n\n                           {rt7} Ranged eyes {rt7}\n                                \n  |cred--------------------||r {rt8} Boss {rt8} |cred--------------------||r\n     |chunterRanged players||r                 ||chunterRanged players||r\n                           {rt7} Melee eyes {rt7}\n               |cdeathknightMelee players||r     ||cdeathknightMelee players||r\n                                  ||cpurpleEntrance||r",
		["CategoryId"] = 22948398,
	},
	[945097202] = {
		["Updated"] = 1670613270,
		["Name"] = "Princess Huhuran",
		["Contents"] = "- ||cgreenNoxious Poison||r {icon spell_nature_corrosivebreath} silences random player and everyone in |cblue15yd||r range.\n- |cgreenWyvern Sting||r {icon inv_spear_02} silences 10 players closest to the boss.\n- |cgreenPoison Bolt||r {icon spell_nature_corrosivebreath} hits 9 closest players (enrage phase).\n\n|credEveryone:||r Save CDs for the |credenrage phase (30%)||r.\n\n{tank} ||cwarriorTanks:\n - Boss stacks |cgreenNature DoT||r. Can't be dispelled.\n - Immune to taunt.\n - 1-2 tanks.\n\n{healer} ||cgreenHealers:\n - Position in semi-circle around to boss to reach all players. |cblue15yd||r range check.\n - Don't dispel sleep {icon inv_spear_02} on squishies. Dispel only tanks, healers, or DPS with high HP.\n\n{dps} ||cdeathknightDPS:\n - Ranged spread in a semi-circle around to boss. |cblue15yd||r range check.\n - ||cred9-10 closest players should have 200+ NR for the enrage phase.||r Don't forget to use defensive CDs.\n - {hunter} |chunterHunters||r must dispel Frenzy from the boss.",
		["Id"] = 945097202,
		["UpdateId"] = 4018094529,
		["Backup"] = "- ||cgreenNoxious Poison||r {icon spell_nature_corrosivebreath} silences random player and everyone in |cblue15yd||r range.\n- |cgreenWyvern Sting||r {icon inv_spear_02} silences 10 players closest to the boss.\n- |cgreenPoison Bolt||r {icon spell_nature_corrosivebreath} hits 9 closest players (enrage phase).\n\n|credEveryone:||r Save CDs for the |credenrage phase (30%)||r.\n\n{tank} ||cwarriorTanks:\n - Boss stacks |cgreenNature DoT||r. Can't be dispelled.\n - Immune to taunt.\n - 1-2 tanks.\n\n{healer} ||cgreenHealers:\n - Position in semi-circle around to boss to reach all players. |cblue15yd||r range check.\n - Don't dispel sleep {icon inv_spear_02} on squishies. Dispel only tanks, healers, or DPS with high HP.\n\n{dps} ||cdeathknightDPS:\n - Ranged spread in a semi-circle around to boss. |cblue15yd||r range check.\n - ||cred9-10 closest players should have 200+ NR for the enrage phase.||r Don't forget to use defensive CDs.\n - {hunter} |chunterHunters||r must dispel Frenzy from the boss.",
		["CategoryId"] = 22948398,
	},
	[576860867] = {
		["Updated"] = 1670782385,
		["Name"] = "Fankriss",
		["Backup"] = "{tank} |cwarriorTanks:||r\n - {rt1} and {rt2} switch on the boss after |cred3 stacks of Mortal Wound||r.\n - Taunt and tank the big worms when they spawn.\n - Try to tank the small adds when they arrive.\n\n{dps} |cdeathknightDPS:||r\n - |credKill priority:|r Big worms -> small adds -> boss {rt8}.\n - Don't aggro the big worms, they hurt.\n - Don't aggro the whole group of small adds, you'll die.\n\n{healer} |cgreenHealers:||r\n - Spot heal DPS that aggro adds.",
		["Id"] = 576860867,
		["UpdateId"] = 1183007512,
		["Contents"] = "{tank} |cwarriorTanks:||r\n - {rt1} and {rt2} switch on the boss after |cred3 stacks of Mortal Wound||r.\n - Taunt and tank the big worms when they spawn.\n - Try to tank the small adds when they arrive.\n\n{dps} |cdeathknightDPS:||r\n - |credKill priority:|r Big worms -> small adds -> boss {rt8}.\n - Don't aggro the big worms, they hurt.\n - Don't aggro the whole group of small adds, you'll die.\n\n{healer} |cgreenHealers:||r\n - Spot heal DPS that aggro adds.",
		["CategoryId"] = 22948398,
	},
	[344920195] = {
		["Updated"] = 1670613765,
		["Name"] = "Bugs: Kri Last",
		["Backup"] = "||credKill order:||r Yauj {rt8} -> Vem {rt7} -> Kri {rt6}\n\nBoss positions in the room: \n - ||cblueLeft:||r Yauj {rt7}. Tanked by {rt1}.\n - ||cblueMiddle:||r Kri {rt8}. Tanked by {rt2}.\n - ||cblueRight:||r Vem {rt6}. Tanked by {rt4} in one of the alcoves.\n\nKri {rt8}: Cleave, ||cgreenToxic Volley||r, ||credDeath = Poison Cloud||r.\n - |corangeThrash||r ability. Especially deadly when Kri is the last boss.\nYauj {rt7}: ||cwarlockAoE Fear||r (resets threat), ||credHeal||r, Dispel. Death = Adds.\nVem {rt6}: Knocks away tank, charges random player in LoS.\n\n{shaman} ||cshamanShamans:||r Tremor Totem {icon spell_nature_tremortotem}, Cleansing Totem {icon spell_nature_diseasecleansingtotem}\n{healer} ||cgreenHealers:||r Dispel poison and fear.\n{dps} ||cdeathknightDPS:||r Don't die and interrupt Yauj's heal.\n\n{tank} ||cwarriorTanks:||r |credSave your 50% CD when Kri is the last boss.||r Let other tanks tank the boss when your CD ends.",
		["Id"] = 344920195,
		["UpdateId"] = 2557835649,
		["Contents"] = "||credKill order:||r Yauj {rt8} -> Vem {rt7} -> Kri {rt6}\n\nBoss positions in the room: \n - ||cblueLeft:||r Yauj {rt7}. Tanked by {rt1}.\n - ||cblueMiddle:||r Kri {rt8}. Tanked by {rt2}.\n - ||cblueRight:||r Vem {rt6}. Tanked by {rt4} in one of the alcoves.\n\nKri {rt8}: Cleave, ||cgreenToxic Volley||r, ||credDeath = Poison Cloud||r.\n - |corangeThrash||r ability. Especially deadly when Kri is the last boss.\nYauj {rt7}: ||cwarlockAoE Fear||r (resets threat), ||credHeal||r, Dispel. Death = Adds.\nVem {rt6}: Knocks away tank, charges random player in LoS.\n\n{shaman} ||cshamanShamans:||r Tremor Totem {icon spell_nature_tremortotem}, Cleansing Totem {icon spell_nature_diseasecleansingtotem}\n{healer} ||cgreenHealers:||r Dispel poison and fear.\n{dps} ||cdeathknightDPS:||r Don't die and interrupt Yauj's heal.\n\n{tank} ||cwarriorTanks:||r |credSave your 50% CD when Kri is the last boss.||r Let other tanks tank the boss when your CD ends.",
		["CategoryId"] = 22948398,
	},
	[1499618519] = {
		["Updated"] = 1690224418,
		["Name"] = "Magtheridon N",
		["CategoryId"] = 603917480,
		["Id"] = 1499618519,
		["UpdateId"] = 3305195844,
		["Contents"] = "Room layout\n|cred-------------------\n                  {rt8}\n    G4 {rt4}  |credBoss||r  G3 {rt3}\n                  {rt8}\n\n G5 {rt5}                   G2 {rt2}\n\n               G1 {rt1}\n          ||cpurpleEntrance||r\n\n{tank} |cwarriorTanks\n||cred-------------------\nBuff: {rt1} {rt2}\nKeg: {rt3} {rt4}\nMyrep: {rt5}\n\n{dps} |crogueDPS:\n||cred-------------------\n|cblueP1||r kill order: {rt1} >>> {rt2} >>> {rt3} >>> {rt4} >>> {rt5}\n\n{icon ability_creature_cursed_02} |credP2 Cubes\n||cred-------------------\n|cgreen30s||r debuff duration, single clicker per cube needed\n - G1 {rt1}: Riddi\n - G2 {rt2}: Moguso\n - G3 {rt3}: Ratrat\n - G4 {rt4}: Emu\n - G5 {rt5}: Raaru\n - |credBackup:||r Zelfie\n\n{warlock} |cwarlockWarlocks:||r {icon spell_shadow_cripple}Banish Abyssals in |cblueP1\n{shaman} |cshamanShamans:||r {bl}Bloodlust in |cblueP2||r right before successful cubes",
		["Backup"] = "Room layout\n|cred-------------------\n                  {rt8}\n    G4 {rt4}  |credBoss||r  G3 {rt3}\n                  {rt8}\n\n G5 {rt5}                   G2 {rt2}\n\n               G1 {rt1}\n          ||cpurpleEntrance||r\n\n{tank} |cwarriorTanks\n||cred-------------------\nBuff: {rt1} {rt2}\nKeg: {rt3} {rt4}\nMyrep: {rt5}\n\n{dps} |crogueDPS:\n||cred-------------------\n|cblueP1||r kill order: {rt1} >>> {rt2} >>> {rt3} >>> {rt4} >>> {rt5}\n\n{icon ability_creature_cursed_02} |credP2 Cubes\n||cred-------------------\n|cgreen30s||r debuff duration, single clicker per cube needed\n - G1 {rt1}: Riddi\n - G2 {rt2}: Moguso\n - G3 {rt3}: Ratrat\n - G4 {rt4}: Emu\n - G5 {rt5}: Raaru\n - |credBackup:||r Zelfie\n\n{warlock} |cwarlockWarlocks:||r {icon spell_shadow_cripple}Banish Abyssals in |cblueP1\n{shaman} |cshamanShamans:||r {bl}Bloodlust in |cblueP2||r right before successful cubes",
	},
	[844996491] = {
		["Updated"] = 1670267565,
		["Name"] = "Battleguard Sartura",
		["Backup"] = "|credKill order:||r Guard {rt8} -> Guard {rt7} -> Guard {rt6} -> Boss {rt5}.\n\n{tank} |cwarriorTank assignments:||r\n - {rt8} tanked by {rt1}.\n - {rt7} tanked by {rt2}.\n - {rt6} tanked by {rt3}.\n - {rt5} tanked by {rt4}.\n\n|credPositioning:||r\n - Spread guards and boss across the room.\n - Players should be spread to avoid multiple deaths by Whirlwind.\n\n|cblueOverview:||r\n - Boss and guards reset aggro randomly.\n - All mobs are stunnable! |credStun-lock||r the current target.\n    - Stuns have diminishing returns tho.\n - Boss and guards |credfixate on a random player and Whirlwind!||r\n\n{tank} |cwarriorTanks:||r Spread out and help with stuns.\n{dps} |cdeathknightDPS:||r Burst the guards ASAP (use CDs). Rotate stuns. Run away from Whirlwind.\n{healer} |cgreenHealers:||r Spread out to cover the whole raid. |cblueFast heals save lives.||r",
		["Id"] = 844996491,
		["UpdateId"] = 2399713483,
		["Contents"] = "|credKill order:||r Guard {rt8} -> Guard {rt7} -> Guard {rt6} -> Boss {rt5}.\n\n{tank} |cwarriorTank assignments:||r\n - {rt8} tanked by {rt1}.\n - {rt7} tanked by {rt2}.\n - {rt6} tanked by {rt3}.\n - {rt5} tanked by {rt4}.\n\n|credPositioning:||r\n - Spread guards and boss across the room.\n - Players should be spread to avoid multiple deaths by Whirlwind.\n\n|cblueOverview:||r\n - Boss and guards reset aggro randomly.\n - All mobs are stunnable! |credStun-lock||r the current target.\n    - Stuns have diminishing returns tho.\n - Boss and guards |credfixate on a random player and Whirlwind!||r\n\n{tank} |cwarriorTanks:||r Spread out and help with stuns.\n{dps} |cdeathknightDPS:||r Burst the guards ASAP (use CDs). Rotate stuns. Run away from Whirlwind.\n{healer} |cgreenHealers:||r Spread out to cover the whole raid. |cblueFast heals save lives.||r",
		["CategoryId"] = 22948398,
	},
	[802941985] = {
		["Updated"] = 1690224590,
		["Name"] = "High King Maulgar N",
		["Backup"] = "Kill order\n||cred-------------------\n{rt8} Blindeye the Seer: {icon spell_holy_heal}Heal, {icon spell_holy_powerwordshield}Shield, {icon spell_holy_prayerofhealing02}Prayer of Healing\n{rt7} Olm the Summoner: {icon spell_shadow_deathcoil}Death Coil, {icon spell_shadow_shadowfury}stacking DoT on {tank}, {icon spell_shadow_summonfelguard}summons Felhunter\n|credRanged only:\n{rt2} Krosh Firehand: {icon spell_holy_excorcism_02}Blast Nova |cred(15yd AoE)||r, {icon spell_fire_flamebolt}Fireball, {icon spell_arcane_arcaneresilience}Spell Shield\n{rt3} Kiggler the Crazed: {icon spell_nature_wispsplode}Arcane Explosion |cred(30yd AoE)||r, {icon spell_nature_lightning}Lightning Bolt, {icon spell_arcane_arcane04}Silence, {icon spell_nature_polymorph}Polymorph\n|credMelee:\n{rt6} High King Maulgar: {icon ability_warrior_cleave}Cleave, {icon inv_gauntlets_05}Knockback, {icon ability_whirlwind}Whirlwind |cred(8yd AoE)||r\n    - |credEnrage||r <50% HP: {icon ability_golemthunderclap}Fear |cred(8yd AoE)||r + {icon ability_warrior_charge}Charge\n\n{tank} |cwarriorTanks:\n||cred-------------------\n{rt8} (stack with {rt7}): |cpaladinMyrep\n{rt7} (stack with {rt8}): |cwarriorAshoganky\n{rt6} (near the entrance): |cwarriorBuff\n{rt2} (tank where he stands): |cmageZelfie\n{rt3} (tank where he stands): |cdruidRatrat\n\n{dps} |crogueMelee DPS:\n||cred-------------------\n{icon ability_creature_cursed_02} Don't go near {rt2} or {rt3}\n{icon ability_creature_cursed_02} Run away from {rt6} whirlwind\n\n{shaman} |cshamanShamans:||r |credNO BL||r, save for Gruul",
		["Id"] = 802941985,
		["UpdateId"] = 1468353687,
		["Contents"] = "Kill order\n||cred-------------------\n{rt8} Blindeye the Seer: {icon spell_holy_heal}Heal, {icon spell_holy_powerwordshield}Shield, {icon spell_holy_prayerofhealing02}Prayer of Healing\n{rt7} Olm the Summoner: {icon spell_shadow_deathcoil}Death Coil, {icon spell_shadow_shadowfury}stacking DoT on {tank}, {icon spell_shadow_summonfelguard}summons Felhunter\n|credRanged only:\n{rt2} Krosh Firehand: {icon spell_holy_excorcism_02}Blast Nova |cred(15yd AoE)||r, {icon spell_fire_flamebolt}Fireball, {icon spell_arcane_arcaneresilience}Spell Shield\n{rt3} Kiggler the Crazed: {icon spell_nature_wispsplode}Arcane Explosion |cred(30yd AoE)||r, {icon spell_nature_lightning}Lightning Bolt, {icon spell_arcane_arcane04}Silence, {icon spell_nature_polymorph}Polymorph\n|credMelee:\n{rt6} High King Maulgar: {icon ability_warrior_cleave}Cleave, {icon inv_gauntlets_05}Knockback, {icon ability_whirlwind}Whirlwind |cred(8yd AoE)||r\n    - |credEnrage||r <50% HP: {icon ability_golemthunderclap}Fear |cred(8yd AoE)||r + {icon ability_warrior_charge}Charge\n\n{tank} |cwarriorTanks:\n||cred-------------------\n{rt8} (stack with {rt7}): |cpaladinMyrep\n{rt7} (stack with {rt8}): |cwarriorAshoganky\n{rt6} (near the entrance): |cwarriorBuff\n{rt2} (tank where he stands): |cmageZelfie\n{rt3} (tank where he stands): |cdruidRatrat\n\n{dps} |crogueMelee DPS:\n||cred-------------------\n{icon ability_creature_cursed_02} Don't go near {rt2} or {rt3}\n{icon ability_creature_cursed_02} Run away from {rt6} whirlwind\n\n{shaman} |cshamanShamans:||r |credNO BL||r, save for Gruul",
		["CategoryId"] = 555034898,
	},
	[1834345531] = {
		["Updated"] = 1670263878,
		["Name"] = "Viscidus",
		["Backup"] = "|credThree phases:||r\n 1. Freeze the boss (boss must take |cmage200 frost damage attacks||r).\n 2. Shatter the boss (|crogue75 melee attacks||r).\n 3. Kill globs (spawn around the room, move to the boss).\n - |credRepeat||r untill the boss dies.\n\n|credImportant:||r Don't stand in the |cgreenpoison clouds||r.\n \n{shaman} |cshamanShamans:||r Place Cleansing Totem {icon spell_nature_diseasecleansingtotem} in the center of the room.\n\n{dps} |cdeathknightDPS:||r\n - Use frost damage weapons, Frost Oils {icon inv_potion_20}, frost spels, etc.\n - Kill the globs in P3. Each |credkilled||r glob reduced boss HP by |cred5%||r.\n\n{healer} |cgreenHealers:||r\n - Dispel the groups without Cleansing Totems ASAP.",
		["Id"] = 1834345531,
		["UpdateId"] = 3330770830,
		["Contents"] = "|credThree phases:||r\n 1. Freeze the boss (boss must take |cmage200 frost damage attacks||r).\n 2. Shatter the boss (|crogue75 melee attacks||r).\n 3. Kill globs (spawn around the room, move to the boss).\n - |credRepeat||r untill the boss dies.\n\n|credImportant:||r Don't stand in the |cgreenpoison clouds||r.\n \n{shaman} |cshamanShamans:||r Place Cleansing Totem {icon spell_nature_diseasecleansingtotem} in the center of the room.\n\n{dps} |cdeathknightDPS:||r\n - Use frost damage weapons, Frost Oils {icon inv_potion_20}, frost spels, etc.\n - Kill the globs in P3. Each |credkilled||r glob reduced boss HP by |cred5%||r.\n\n{healer} |cgreenHealers:||r\n - Dispel the groups without Cleansing Totems ASAP.",
		["CategoryId"] = 22948398,
	},
}
AngryAssign_Categories = {
	[603917480] = {
		["Id"] = 603917480,
		["Name"] = "Magtheridon",
	},
	[22948398] = {
		["Id"] = 22948398,
		["Name"] = "AQ40",
	},
	[555034898] = {
		["Id"] = 555034898,
		["Name"] = "Gruul's Lair",
	},
}
AngryAssign_State = {
	["locked"] = true,
	["directionUp"] = false,
	["display"] = {
		["y"] = -46.57360838704994,
		["x"] = 21.26777628512389,
		["point"] = "TOPLEFT",
		["scale"] = 1,
		["hidden"] = false,
		["width"] = 484.4763407458413,
	},
	["tree"] = {
		["groups"] = {
			["1499618519"] = true,
			["-6039174801499618519"] = true,
			["379406110"] = true,
			["214789270"] = true,
			[-603917480] = true,
			["1094759972"] = true,
			["1936460464"] = true,
			["1502548296"] = true,
			["-555034898"] = true,
			["-603917480-3104737875"] = false,
			["1556566058"] = true,
			["1416669210"] = true,
			["1342875454"] = true,
			["-6039174802175879919"] = true,
			["2175879919"] = true,
			[-3104737875] = false,
			[-555034898] = true,
			["-603917480"] = true,
			["1583056124"] = true,
			["588579974"] = true,
			["1095919676"] = true,
			[-670074350] = true,
			["231025117"] = true,
			["1258583331"] = true,
			["1834345531"] = true,
			["-555034898414441359"] = true,
			["355235451"] = true,
			["1694692832"] = true,
			["1574022645"] = true,
			["748191779"] = true,
			["945097202"] = true,
			["576860867"] = true,
			["-603917480-670074350"] = true,
			[-22948398] = true,
			["844996491"] = true,
			["344920195"] = true,
			["802941985"] = true,
			["414441359"] = true,
		},
		["scrollvalue"] = 0,
		["selected"] = "-555034898802941985",
		["treesizable"] = true,
		["treewidth"] = 175,
		["fullwidth"] = 1080.648576529607,
	},
	["window"] = {
		["height"] = 630.3598099770952,
		["top"] = 728.5528576084528,
		["left"] = 693.2746367138774,
		["width"] = 1114.648613015743,
	},
}
AngryAssign_Config = {
	["backdropColor"] = "02020280",
	["backdropShow"] = true,
}
